# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# Dimitris Glezos <glezos@transifex.com>, 2011
# Hajime Taira <htaira@redhat.com>, 2011
# hyuugabaru <hyu_gabaru@yahoo.co.jp>, 2009
# Kiyoto Hashida <khashida@redhat.com>, 2008, 2009, 2010
# Kiyoto Hashida <khashida@redhat.com>, 2006, 2007
# noriko <noriko@fedoraproject.org>, 2013
# Noriko Mizumoto <noriko@redhat.com>, 2006, 2008
# Tomoyuki KATO <tomo@dream.daynight.jp>, 2011-2013
# 高一人参 @欠陥遺伝子 <www.carrotsoft@gmail.com>, 2011
# Noriko Mizumoto <noriko@redhat.com>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-01-15 16:27+0100\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2016-01-14 11:04-0500\n"
"Last-Translator: Noriko Mizumoto <noriko@redhat.com>\n"
"Language-Team: Japanese (http://www.transifex.com/projects/p/fedora/language/"
"ja/)\n"
"Language: ja\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Generator: Zanata 3.8.3\n"

#: ../setroubleshoot.desktop.in.h:1
msgid "SELinux Troubleshooter"
msgstr "SELinux Troubleshooter"

#: ../setroubleshoot.desktop.in.h:2
msgid "Troubleshoot SELinux access denials"
msgstr "SELinux アクセス拒否のトラブルシューティング"

#: ../setroubleshoot.desktop.in.h:3
msgid "policy;security;selinux;avc;permission;mac;alert;sealert;"
msgstr "policy;security;selinux;avc;permission;mac;alert;sealert;"

#: ../src/setroubleshoot/audit_data.py:903
#, python-format
msgid "port %s"
msgstr "ポート %s"

#: ../src/setroubleshoot/audit_data.py:905
#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
msgid "Unknown"
msgstr "不明"

#: ../src/setroubleshoot/audit_data.py:995
#, python-format
msgid "%s \n"
"**** Invalid AVC allowed in current policy ***\n"
msgstr "%s \n"
"**** 無効な AVC が現在のポリシーで許可されています ***\n"

#: ../src/setroubleshoot/audit_data.py:997
#, python-format
msgid ""
"%s \n"
"**** Invalid AVC dontaudited in current policy.  'semodule -B' will turn on "
"dontaudit rules. ***\n"
msgstr ""
"%s \n"
"**** 無効な AVC が現在のポリシーで dontaudit されています。  'semodule -B' が dontaudit "
"ルールをオンにします。 ***\n"

#: ../src/setroubleshoot/audit_data.py:999
msgid "Must call policy_init first"
msgstr "policy_init を最初にコールしなければなりません"

#: ../src/setroubleshoot/audit_data.py:1001
#, python-format
msgid "%s \n"
"**** Invalid AVC bad target context. ***\n"
msgstr "%s \n"
"**** 無効な AVC 不正ターゲットコンテキストです。 ***\n"

#: ../src/setroubleshoot/audit_data.py:1003
#, python-format
msgid "%s \n"
"**** Invalid AVC bad source context. ***\n"
msgstr "%s \n"
"**** 無効な AVC 不正ソースコンテキストです。 ***\n"

#: ../src/setroubleshoot/audit_data.py:1005
#, python-format
msgid "%s \n"
"**** Invalid AVC bad type class ***\n"
msgstr "%s \n"
"**** 無効な AVC 不正タイプクラスです ***\n"

#: ../src/setroubleshoot/audit_data.py:1007
#, python-format
msgid "%s \n"
"**** Invalid AVC bad permission ***\n"
msgstr "%s \n"
"**** 無効な AVC 不正認可です ***\n"

#: ../src/setroubleshoot/audit_data.py:1009
msgid "Error during access vector computation"
msgstr "アクセスベクターの演算時にエラーが発生しました"

#: ../src/setroubleshoot/browser.py:171 ../gui/browser.glade.h:12
msgid "SELinux Alert Browser"
msgstr "SELinux 通知ブラウザー"

#: ../src/setroubleshoot/browser.py:175 ../gui/browser.glade.h:19
msgid "The source process:"
msgstr "原因プロセス:"

#: ../src/setroubleshoot/browser.py:180 ../gui/browser.glade.h:15
msgid "Yes"
msgstr "はい"

#: ../src/setroubleshoot/browser.py:182 ../gui/browser.glade.h:17
msgid "No"
msgstr "いいえ"

#: ../src/setroubleshoot/browser.py:187 ../gui/browser.glade.h:20
msgid "Attempted this access:"
msgstr "試行したアクセス:"

#: ../src/setroubleshoot/browser.py:201 ../gui/browser.glade.h:11
msgid "SETroubleshoot Details Window"
msgstr "SETroubleshootの詳細のウィンドウ"

#: ../src/setroubleshoot/browser.py:204 ../gui/browser.glade.h:14
msgid "Would you like to receive alerts?"
msgstr "通知を受け取りますか？"

#: ../src/setroubleshoot/browser.py:208 ../gui/browser.glade.h:24
msgid "Notify Admin"
msgstr "管理者に通知"

#: ../src/setroubleshoot/browser.py:211 ../src/setroubleshoot/browser.py:217
#: ../gui/browser.glade.h:8
msgid "Troubleshoot"
msgstr "トラブルシュート"

#: ../src/setroubleshoot/browser.py:214 ../gui/browser.glade.h:26
msgid "Details"
msgstr "詳細"

#: ../src/setroubleshoot/browser.py:221 ../gui/browser.glade.h:7
msgid "SETroubleshoot Alert List"
msgstr "SETroubleshoot 通知リスト"

#: ../src/setroubleshoot/browser.py:223 ../gui/browser.glade.h:33
msgid "List All Alerts"
msgstr "すべての通知の一覧"

#: ../src/setroubleshoot/browser.py:270
msgid "#"
msgstr "#"

#: ../src/setroubleshoot/browser.py:270
msgid "Source Process"
msgstr "ソースプロセス"

#: ../src/setroubleshoot/browser.py:270
msgid "Attempted Access"
msgstr "試行したアクセス"

#: ../src/setroubleshoot/browser.py:270
msgid "On this"
msgstr "試行の対象"

#: ../src/setroubleshoot/browser.py:270
msgid "Occurred"
msgstr "発生回数"

#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
msgid "Status"
msgstr "ステータス"

#: ../src/setroubleshoot/browser.py:344 ../src/setroubleshoot/browser.py:786
#: ../src/setroubleshoot/browser.py:830
msgid "Notify"
msgstr "通知する"

#: ../src/setroubleshoot/browser.py:345
msgid "Notify alert in the future."
msgstr "後ほど警告を表示します。"

#: ../src/setroubleshoot/browser.py:348 ../src/setroubleshoot/browser.py:788
#: ../src/setroubleshoot/browser.py:828 ../gui/browser.glade.h:27
msgid "Ignore"
msgstr "無視"

#: ../src/setroubleshoot/browser.py:349 ../gui/browser.glade.h:28
msgid "Ignore alert in the future."
msgstr "次回から警告を無視します。"

#: ../src/setroubleshoot/browser.py:385
msgid "<b>If you were trying to...</b>"
msgstr "<b>次を試行していた場合...</b>"

#: ../src/setroubleshoot/browser.py:394
msgid "<b>Then this is the solution.</b>"
msgstr "<b>これが解決策です</b>"

#: ../src/setroubleshoot/browser.py:413 ../src/setroubleshoot/browser.py:549
msgid "If "
msgstr "もし"

#: ../src/setroubleshoot/browser.py:501
msgid "Plugin\n"
"Details"
msgstr "プラグイン\n"
"詳細"

#: ../src/setroubleshoot/browser.py:516
msgid "Report\n"
"Bug"
msgstr "バグ\n"
"報告"

#: ../src/setroubleshoot/browser.py:544
#, python-format
msgid "Plugin: %s "
msgstr "プラグイン: %s "

#: ../src/setroubleshoot/browser.py:611
msgid "Unable to grant access."
msgstr "アクセスを認可できません"

#: ../src/setroubleshoot/browser.py:642 ../src/setroubleshoot/browser.py:784
#, python-format
msgid "Alert %d of %d"
msgstr "通知 %d / %d"

#: ../src/setroubleshoot/browser.py:767
#, python-format
msgid "On this %s:"
msgstr "対象 %s:"

#: ../src/setroubleshoot/browser.py:815 ../src/setroubleshoot/browser.py:821
#: ../src/setroubleshoot/signature.py:391
msgid "N/A"
msgstr "N/A"

#: ../src/setroubleshoot/browser.py:862 ../src/setroubleshoot/browser.py:863
#: ../gui/browser.glade.h:31
msgid "No Alerts"
msgstr "通知なし"

#: ../src/setroubleshoot/browser.py:881
msgid "SELinux has detected a problem."
msgstr "SELinux は問題を検出しました。"

#: ../src/setroubleshoot/browser.py:987
msgid "Sealert Error"
msgstr "Sealert エラー"

#: ../src/setroubleshoot/browser.py:998
msgid "Sealert Message"
msgstr "Sealert メッセージ"

#. -----------------------------------------------------------------------------
#: ../src/setroubleshoot/errcode.py:71
msgid "signature not found"
msgstr "署名が見つかりませんでした"

#: ../src/setroubleshoot/errcode.py:72
msgid "multiple signatures matched"
msgstr "複数の署名が一致しました"

#: ../src/setroubleshoot/errcode.py:73
msgid "id not found"
msgstr "ID が見つかりませんでした"

#: ../src/setroubleshoot/errcode.py:74
msgid "database not found"
msgstr "データベースが見つかりませんでした"

#: ../src/setroubleshoot/errcode.py:75
msgid "item is not a member"
msgstr "アイテムはメンバーではありません"

#: ../src/setroubleshoot/errcode.py:76
msgid "illegal to change user"
msgstr "ユーザーの変更は不正です"

#: ../src/setroubleshoot/errcode.py:77
msgid "method not found"
msgstr "メソッドが見つかりませんでした"

#: ../src/setroubleshoot/errcode.py:78
msgid "cannot create GUI"
msgstr "GUI を作成できません"

#: ../src/setroubleshoot/errcode.py:79
msgid "value unknown"
msgstr "値が不明です"

#: ../src/setroubleshoot/errcode.py:80
msgid "cannot open file"
msgstr "ファイルを開けません"

#: ../src/setroubleshoot/errcode.py:81
msgid "invalid email address"
msgstr "無効な電子メールアドレス"

#. gobject IO Errors
#: ../src/setroubleshoot/errcode.py:84
msgid "socket error"
msgstr "ソケットエラー"

#: ../src/setroubleshoot/errcode.py:85
msgid "connection has been broken"
msgstr "接続が遮断されました"

#: ../src/setroubleshoot/errcode.py:86
msgid "Invalid request. The file descriptor is not open"
msgstr "無効な要求です。ファイル記述子は開いていません"

#: ../src/setroubleshoot/errcode.py:88
msgid "insufficient permission to modify user"
msgstr "ユーザーを変更するのに十分な権限がありません。"

#: ../src/setroubleshoot/errcode.py:89
msgid "authentication failed"
msgstr "認証は失敗しました"

#: ../src/setroubleshoot/errcode.py:90
msgid "user prohibited"
msgstr "ユーザーは禁止されています。"

#: ../src/setroubleshoot/errcode.py:91
msgid "not authenticated"
msgstr "認証されていません"

#: ../src/setroubleshoot/errcode.py:92
msgid "user lookup failed"
msgstr "ユーザーの検索に失敗しました"

#: ../src/setroubleshoot/gui_utils.py:53 ../src/sealert:531
#, c-format, python-format
msgid "Opps, %s hit an error!"
msgstr "%s  がエラーです!"

#: ../src/setroubleshoot/gui_utils.py:55 ../gui/fail_dialog.glade.h:1
msgid "Error"
msgstr "エラー"

#: ../src/setroubleshoot/Plugin.py:81
msgid ""
"you want to allow $SOURCE_BASE_PATH to have $ACCESS access on the "
"$TARGET_BASE_PATH $TARGET_CLASS"
msgstr ""
"$TARGET_BASE_PATH $TARGET_CLASS に "
"$ACCESSアクセスをするために、$SOURCE_BASE_PATHを許可しますか?"

#: ../src/run_cmd.py:172
msgid "Input: "
msgstr "入力: "

#: ../src/run_cmd.py:255
msgid "Enter Password"
msgstr "パスワード入力"

#: ../src/run_cmd.py:268
msgid "Password: "
msgstr "パスワード: "

#: ../src/run_cmd.py:367
msgid "SELinux Fix"
msgstr "SELinux Fix"

#: ../src/run_cmd.py:378
msgid "Command"
msgstr "コマンド"

#: ../src/run_cmd.py:388
msgid "Run Command"
msgstr "コマンドを実行"

#: ../src/run_cmd.py:391
msgid "Stop Command"
msgstr "コマンドを停止"

#: ../src/run_cmd.py:413
msgid "Warning: You are responsible for verifying this command is correct"
msgstr "警告: ユーザーにはこのコマンドが正しいことを確認する責任があります"

#: ../src/run_cmd.py:455
msgid "Not Run Yet"
msgstr "まだ実行しない"

#: ../src/run_cmd.py:466
msgid "Running..."
msgstr "実行中..."

#: ../src/run_cmd.py:481
#, python-format
msgid "Interrupted, exit on signal %d"
msgstr "妨害されました、シグナル %d で終了します"

#: ../src/run_cmd.py:483
msgid "Success"
msgstr "成功"

#: ../src/run_cmd.py:485
#, python-format
msgid "Failed, exit status = %d"
msgstr "失敗、終了ステータス = %d"

#: ../src/run_cmd.py:487
msgid "Done: "
msgstr "完了: "

#: ../src/setroubleshoot/server.py:191
#, python-format
msgid " For complete SELinux messages. run sealert -l %s"
msgstr "完全な SELinux メッセージを見るには、sealert -l %s を実行します"

#: ../src/setroubleshoot/server.py:377
#, python-format
msgid "The user (%s) cannot modify data for (%s)"
msgstr "ユーザー(%s) は (%s) 用のデータを修正できません。"

#: ../src/setroubleshoot/server.py:440 ../src/sealert:291
msgid "Started"
msgstr "開始済み"

#: ../src/setroubleshoot/server.py:487
msgid "AVC"
msgstr "AVC"

#: ../src/setroubleshoot/server.py:553
msgid "Audit Listener"
msgstr "リスナーの監査"

#: ../src/setroubleshoot/signature.py:74
msgid "Never Ignore"
msgstr "無視しない"

#: ../src/setroubleshoot/signature.py:75
msgid "Ignore Always"
msgstr "常に無視する"

#: ../src/setroubleshoot/signature.py:76
msgid "Ignore After First Alert"
msgstr "最初の通知以後は無視"

#: ../src/setroubleshoot/signature.py:193
msgid "directory"
msgstr "ディレクトリ"

#: ../src/setroubleshoot/signature.py:194
msgid "semaphore"
msgstr "セマフォ"

#: ../src/setroubleshoot/signature.py:195
msgid "shared memory"
msgstr "共有メモリー"

#: ../src/setroubleshoot/signature.py:196
msgid "message queue"
msgstr "メッセージキュー"

#: ../src/setroubleshoot/signature.py:197
msgid "message"
msgstr "メッセージ"

#: ../src/setroubleshoot/signature.py:198
msgid "file"
msgstr "ファイル"

#: ../src/setroubleshoot/signature.py:199
msgid "socket"
msgstr "ソケット"

#: ../src/setroubleshoot/signature.py:200
msgid "process"
msgstr "プロセス"

#: ../src/setroubleshoot/signature.py:201
msgid "filesystem"
msgstr "ファイルシステム"

#: ../src/setroubleshoot/signature.py:202
msgid "node"
msgstr "ノード"

#: ../src/setroubleshoot/signature.py:203
msgid "capability"
msgstr "能力"

#: ../src/setroubleshoot/signature.py:376
#, python-format
msgid "%s has a permissive type (%s). This access was not denied."
msgstr "%s は許容タイプ (%s) を持ちます。このアクセスは拒否されませんでした。"

#: ../src/setroubleshoot/signature.py:379
msgid "SELinux is in permissive mode. This access was not denied."
msgstr "SELinuxはpermissiveモードです。このアクセスは拒否されませんでした。"

#: ../src/setroubleshoot/signature.py:432
#, python-format
msgid "SELinux is preventing %s from using the %s access on a process."
msgstr "SELinux により %s がプロセスにおいて %s アクセスを使用できません"

#: ../src/setroubleshoot/signature.py:432
#, python-format
msgid "SELinux is preventing %s from using the '%s' accesses on a process."
msgstr "SELinux により %s がプロセスにおいて '%s' アクセスを使用できません"

#: ../src/setroubleshoot/signature.py:435
#, python-format
msgid "SELinux is preventing %s from using the %s capability."
msgstr "SELinux により %s が %s 能力を使用できません"

#: ../src/setroubleshoot/signature.py:435
#, python-format
msgid "SELinux is preventing %s from using the '%s' capabilities."
msgstr "SELinux により %s が '%s' 能力を使用できません"

#: ../src/setroubleshoot/signature.py:437
#, python-format
msgid "SELinux is preventing %s from %s access on the %s labeled %s."
msgstr "%4$s のラベルが付いた %3$s での %1$s による %2$s アクセスが SELinux により阻止されています。"

#: ../src/setroubleshoot/signature.py:437
#, python-format
msgid "SELinux is preventing %s from '%s' accesses on the %s labeled %s."
msgstr "SELinux により %s が '%s' アクセスを %s のラベルがついた %s で拒否されました。"

#: ../src/setroubleshoot/signature.py:438
#, python-format
msgid "SELinux is preventing %s from %s access on the %s %s."
msgstr "SELinux により %s が %s アクセスを %s %s においてできません"

#: ../src/setroubleshoot/signature.py:438
#, python-format
msgid "SELinux is preventing %s from '%s' accesses on the %s %s."
msgstr "SELinux により %s が '%s' アクセスを %s %s においてできません"

#: ../src/setroubleshoot/signature.py:469
msgid "Additional Information:\n"
msgstr "追加情報:\n"

#: ../src/setroubleshoot/signature.py:470
msgid "Source Context"
msgstr "ソースコンテキスト"

#: ../src/setroubleshoot/signature.py:471
msgid "Target Context"
msgstr "ターゲットコンテキスト"

#: ../src/setroubleshoot/signature.py:472
msgid "Target Objects"
msgstr "ターゲットオブジェクト"

#: ../src/setroubleshoot/signature.py:473
msgid "Source"
msgstr "ソース"

#: ../src/setroubleshoot/signature.py:474
msgid "Source Path"
msgstr "ソースパス"

#: ../src/setroubleshoot/signature.py:475
msgid "Port"
msgstr "ポート"

#: ../src/setroubleshoot/signature.py:477
#: ../src/setroubleshoot/signature.py:479
msgid "Host"
msgstr "ホスト"

#: ../src/setroubleshoot/signature.py:480
msgid "Source RPM Packages"
msgstr "ソース RPM パッケージ"

#: ../src/setroubleshoot/signature.py:481
msgid "Target RPM Packages"
msgstr "ターゲット RPM パッケージ"

#: ../src/setroubleshoot/signature.py:482
msgid "Policy RPM"
msgstr "ポリシー RPM"

#: ../src/setroubleshoot/signature.py:483
msgid "Selinux Enabled"
msgstr "Selinux 有効化"

#: ../src/setroubleshoot/signature.py:484
msgid "Policy Type"
msgstr "ポリシータイプ"

#: ../src/setroubleshoot/signature.py:485
msgid "Enforcing Mode"
msgstr "強制モード"

#: ../src/setroubleshoot/signature.py:487
#: ../src/setroubleshoot/signature.py:489
msgid "Host Name"
msgstr "ホスト名"

#: ../src/setroubleshoot/signature.py:494
#: ../src/setroubleshoot/signature.py:496
msgid "Platform"
msgstr "プラットフォーム"

#: ../src/setroubleshoot/signature.py:497
msgid "Alert Count"
msgstr "通知カウント"

#: ../src/setroubleshoot/signature.py:499
msgid "First Seen"
msgstr "最初の画面"

#: ../src/setroubleshoot/signature.py:500
msgid "Last Seen"
msgstr "最後の画面"

#: ../src/setroubleshoot/signature.py:501
msgid "Local ID"
msgstr "ローカル ID"

#: ../src/setroubleshoot/signature.py:503
msgid "Raw Audit Messages"
msgstr "生の監査メッセージ"

#: ../src/setroubleshoot/signature.py:557
#, python-format
msgid "\n"
"\n"
"*****  Plugin %s (%.4s confidence) suggests   "
msgstr "\n"
"\n"
"*****  プラグイン %s (%.4s 信頼性) による示唆"

#: ../src/setroubleshoot/signature.py:560
msgid "*"
msgstr "*"

#: ../src/setroubleshoot/signature.py:561
msgid "\n"
msgstr "\n"

#: ../src/setroubleshoot/signature.py:563
msgid "\n"
"If "
msgstr "\n"
"次のような場合: "

#: ../src/setroubleshoot/signature.py:565
msgid "\n"
"Then "
msgstr "\n"
"このようにします: "

#: ../src/setroubleshoot/signature.py:568
msgid "\n"
"Do\n"
msgstr "\n"
"そして、以下を実行します: \n"

#: ../src/setroubleshoot/signature.py:570
msgid "\n"
"\n"
msgstr "\n"
"\n"

#: ../src/updater.py:18
#, python-format
msgid "current: %s "
msgstr "現在: %s"

#: ../src/updater.py:27
#, python-format
msgid "newer: %s "
msgstr "最新: %s"

#: ../src/seapplet.c:189
msgid "New SELinux security alert"
msgstr "新規の SELinux セキュリティ通知"

#: ../src/seapplet.c:189
msgid "AVC denial, click icon to view"
msgstr "AVC 拒否、アイコンをクリックして表示"

#: ../src/seapplet.c:195 ../src/seapplet.c:246
msgid "Dismiss"
msgstr "解除"

#: ../src/seapplet.c:205 ../src/seapplet.c:256
msgid "Show"
msgstr "表示"

#. set tooltip
#: ../src/seapplet.c:440 ../src/sealert:64
msgid "SELinux AVC denial, click to view"
msgstr "SELinux AVC 拒否、クリックして表示"

#: ../src/sealert:103
msgid "SELinux not enabled, sealert will not run on non SELinux systems"
msgstr "SELinux が有効化されていません。sealert は SELinux が有効なシステム以外では動作しません。"

#: ../src/sealert:150
msgid "Not fixable."
msgstr "修正不可です。"

#: ../src/sealert:157
#, c-format
msgid "Successfully ran %s"
msgstr "%s を正常に実行しました。"

#: ../src/sealert:162
#, c-format
msgid "Plugin %s not valid for %s id"
msgstr "プラグイン %s は %s id には認められていません。"

#: ../src/setroubleshootd:73
msgid "SELinux not enabled, setroubleshootd exiting..."
msgstr "SELinux が有効になっていません。setroubleshootd は終了します..."

#: ../src/setroubleshootd:105
#, c-format
msgid "fork #1 failed: %d (%s)"
msgstr "fork #1 は失敗です: %d (%s)"

#: ../gui/browser.glade.h:1
msgid ""
"Copyright (c) 2010 \n"
"Thomas Liu <tliu@redhat.com>\n"
"Máirín Duffy <duffy@redhat.com>\n"
"Daniel Walsh <dwalsh@redhat.com>\n"
"John Dennis <jdennis@redhat.com>\n"
msgstr ""
"Copyright (c) 2010 \n"
"Thomas Liu <tliu@redhat.com>\n"
"Máirín Duffy <duffy@redhat.com>\n"
"Daniel Walsh <dwalsh@redhat.com>\n"
"John Dennis <jdennis@redhat.com>\n"

#: ../gui/browser.glade.h:9
msgid "Troubleshoot selected alert"
msgstr "SETroubleshootが選択した警告"

#: ../gui/browser.glade.h:10
msgid "Delete Selected Alerts"
msgstr "選択されたアラートを削除"

#: ../gui/browser.glade.h:13
msgid "<b>SELinux has detected a problem.</b>"
msgstr "<b>SELinux は問題を検出しました。</b>"

#: ../gui/browser.glade.h:16
msgid "Turn on alert pop-ups."
msgstr "通知のポップアップを有効化"

#: ../gui/browser.glade.h:18
msgid "Turn off alert pop-ups."
msgstr "通知のポップアップを無効化"

#: ../gui/browser.glade.h:21
msgid "On this file:"
msgstr "このファイル内:"

#: ../gui/browser.glade.h:22
msgid "label"
msgstr "label"

#: ../gui/browser.glade.h:23
msgid ""
"Read alert troubleshoot information.  May require administrative privileges "
"to remedy."
msgstr "トラブルシューティングに関する情報をお読みください。多くの場合、トラブルを解決するには、root権限が必要です。"

#: ../gui/browser.glade.h:25
msgid "Email alert to system administrator."
msgstr "Eメールでシステム管理者に通知"

#: ../gui/browser.glade.h:29
msgid "Delete current alert from the database."
msgstr "現在の通知をデータベースから削除"

#: ../gui/browser.glade.h:30
msgid "Show previous alert."
msgstr "前の通知を表示"

#: ../gui/browser.glade.h:32
msgid "Show next alert."
msgstr "次の通知を表示"

#: ../gui/browser.glade.h:34
msgid "List all alerts in the database."
msgstr "データベースからすべての通知を一覧"

#: ../gui/bug_report.glade.h:1
msgid "Review and Submit Bug Report"
msgstr "確認とバグ報告の提出"

#: ../gui/bug_report.glade.h:2
msgid "<span size='large' weight='bold'>Review and Submit Bug Report</span>"
msgstr "<span size='large' weight='bold'>確認とバグ報告の提出</span>"

#: ../gui/bug_report.glade.h:3
msgid ""
"You may wish to review the error output that will be included in this bug "
"report and modify it to exclude any sensitive data below."
msgstr "このバグ報告に含まれるエラー出力を確認して、以下のような機密情報を排除するために それを修正すると良いでしょう。"

#: ../gui/bug_report.glade.h:4
msgid "Included error output:"
msgstr "含まれているエラー出力:"

#: ../gui/bug_report.glade.h:5
msgid "Submit Report"
msgstr "報告の提出"

#: ../gui/fail_dialog.glade.h:2 ../gui/success_dialog.glade.h:2
msgid ""
"This operation was completed.  The quick brown fox jumped over the lazy dog."
msgstr "このオプションは完了です。「素早い茶色の狐がのろまな犬を飛び越えました。」"

#: ../gui/success_dialog.glade.h:1
msgid "Success!"
msgstr "成功しました!"

#: ../gui/success_dialog.glade.h:3
msgid "button"
msgstr "ボタン"
